---
- name: Install Nginx (for RHEL-based systems)
  dnf:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Install Nginx (for Debian-based systems)
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Start Nginx only if not already running
  shell: |
    if ! pgrep nginx; then
      nginx;
    else
      echo "Nginx already running";
    fi
  when: ansible_os_family in ["Debian", "RedHat"]

- name: Ensure Nginx is responding
  uri:
    url: http://localhost
    status_code: 200
